### ISSUE TITLE
BlackJack Assignment

### ISSUE THREAD

**Issue by Adrienne7** [Adrienne7/ICS3U#2]
BlackJack Assignment to be marked.

**Comment by kevindeslauriers** [comment]
Excellent Work Adrienne.  

Feedback
You need comments inside your code explaining what sections of code will do - this is the only way you will remember later what you are doing.

ONE = 1 is not  necessary constant 
BLACKJACK = 2 is

When you double down you should not be able to hit again.

K 9.5/10
I 15/15
C 8/10
A 9.5/10

93.3%
