### ISSUE TITLE
HorseRacing Assignment - ready to be marked

### ISSUE THREAD

**Issue by Adrienne7** [Adrienne7/ICS3U#4]
https://github.com/Adrienne7/ICS3U/tree/master/Horse%20Racing

**Comment by kevindeslauriers** [comment]
Excellent work Adrienne. You have covered all of the requirements and you were able to create a good Horse Racing Game.

It would have been nice if you made the output and prompts a little more user friendly.  The user should be able to use more then 1 and 2 for options.

K 10/10
I 14.5/15
C 10/10
A 10/10

98.8%
